--------------------------------------------------------
-- Archivo creado  - martes-noviembre-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 901 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INSERTA_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."INSERTA_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 361 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CHECK_IN
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_CHECK_IN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CHECK_OUT
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_CHECK_OUT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONTRATAR_SERVICIOS
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_CONTRATAR_SERVICIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_DEPARTAMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_ID_DEPARTAMENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_INVENTARIO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_ID_INVENTARIO"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_IDPAGO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_IDPAGO"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_IDRESERVA
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_IDRESERVA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SERVICIO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_SERVICIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIO_SEQUENCIA
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."USUARIO_SEQUENCIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."CATEGORIA" 
   (	"ID" NUMBER, 
	"CATEGORIA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHECKIN
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."CHECKIN" 
   (	"ID_CHECKIN" NUMBER, 
	"FECHA_CHECKIN" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ID_RESERVA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."DEPARTAMENTO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(300 BYTE), 
	"UBICACION" VARCHAR2(300 BYTE), 
	"BANOS" VARCHAR2(20 BYTE), 
	"HABITACIONES" VARCHAR2(20 BYTE), 
	"VALORARRIENDO" FLOAT(126), 
	"DESCRIPCION" VARCHAR2(600 BYTE), 
	"FECHA" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(300 BYTE), 
	"HABILITADO" VARCHAR2(20 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVENTARIO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."INVENTARIO" 
   (	"ID_INV" NUMBER, 
	"ID_DEPTO" NUMBER, 
	"PRODUCTO" VARCHAR2(300 BYTE), 
	"CANTIDAD" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(700 BYTE), 
	"CATEGORIA" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCALIDADES
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."LOCALIDADES" 
   (	"ID_LOCALIDAD" NUMBER, 
	"NOMBRE_LOCALIDAD" VARCHAR2(700 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."RESERVA" 
   (	"ID_RESERVA" NUMBER, 
	"FECHA_RESERVA" VARCHAR2(60 BYTE), 
	"CANTIDAD_PERSONAS" VARCHAR2(60 BYTE), 
	"FECHA_SALIDA" VARCHAR2(60 BYTE), 
	"RUT" VARCHAR2(20 BYTE), 
	"ID_DEPARTAMENTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."ROL" 
   (	"ID_ROL" NUMBER, 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICIOS
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."SERVICIOS" 
   (	"ID_SRV" NUMBER, 
	"NOMBRE_SRV" VARCHAR2(800 BYTE), 
	"PRECIO" FLOAT(126), 
	"ID_DEPARTAMENTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."USUARIOS" 
   (	"ID_USUARIO" NUMBER, 
	"RUT" VARCHAR2(15 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"CORREO" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(100 BYTE), 
	"CLAVE" VARCHAR2(20 BYTE), 
	"ID_ROL" NUMBER(4,0) DEFAULT 3
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PORTAFOLIO.CATEGORIA
SET DEFINE OFF;
Insert into PORTAFOLIO.CATEGORIA (ID,CATEGORIA) values ('1','Tecnologia');
Insert into PORTAFOLIO.CATEGORIA (ID,CATEGORIA) values ('2','Materiales de Construcción');
Insert into PORTAFOLIO.CATEGORIA (ID,CATEGORIA) values ('3','Gasfiteria');
Insert into PORTAFOLIO.CATEGORIA (ID,CATEGORIA) values ('4','Electricidad');
Insert into PORTAFOLIO.CATEGORIA (ID,CATEGORIA) values ('5','Seguridad');
Insert into PORTAFOLIO.CATEGORIA (ID,CATEGORIA) values ('6','Electrodomesticos');
Insert into PORTAFOLIO.CATEGORIA (ID,CATEGORIA) values ('7','Muebleria');
REM INSERTING into PORTAFOLIO.CHECKIN
SET DEFINE OFF;
Insert into PORTAFOLIO.CHECKIN (ID_CHECKIN,FECHA_CHECKIN,DESCRIPCION,ID_RESERVA) values ('5','26/11/2019','HOLA MUNDO','825');
Insert into PORTAFOLIO.CHECKIN (ID_CHECKIN,FECHA_CHECKIN,DESCRIPCION,ID_RESERVA) values ('4','26/11/2019','  prueba
                                        ','841');
REM INSERTING into PORTAFOLIO.DEPARTAMENTO
SET DEFINE OFF;
Insert into PORTAFOLIO.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA,DIRECCION,HABILITADO) values ('43','Edificio San Juan de lomas','Putre','2','3','250500','En arriendo','2019-11-12','Av mejillones 4565','0');
Insert into PORTAFOLIO.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA,DIRECCION,HABILITADO) values ('2','Edificio San Juan ','Talca','2','3','365000','En Arriendo','2019-10-29','San Juan 4550','0');
Insert into PORTAFOLIO.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA,DIRECCION,HABILITADO) values ('44','Hostal San Francisco','Huara','3','3','155000','En arriendo','2019-11-12','Domingo Santa Maria 1846','0');
Insert into PORTAFOLIO.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA,DIRECCION,HABILITADO) values ('63','Edificio Santa Clara','Santiago','4','4','1540000','En arriendo','23/11/2019','Matucana 45','0');
Insert into PORTAFOLIO.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA,DIRECCION,HABILITADO) values ('81','GAM','Panquehue','3','3','155000','En reserva','26/11/2019','alameda','1');
REM INSERTING into PORTAFOLIO.INVENTARIO
SET DEFINE OFF;
Insert into PORTAFOLIO.INVENTARIO (ID_INV,ID_DEPTO,PRODUCTO,CANTIDAD,ESTADO,DESCRIPCION,CATEGORIA) values ('41','2','Biblioteca de vidrio','1','Activo','Bibliotecario','Muebleria');
Insert into PORTAFOLIO.INVENTARIO (ID_INV,ID_DEPTO,PRODUCTO,CANTIDAD,ESTADO,DESCRIPCION,CATEGORIA) values ('21','2','Mesa de centro','1','Activo','Mesa de centro living comedor','Muebleria');
REM INSERTING into PORTAFOLIO.LOCALIDADES
SET DEFINE OFF;
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('323','Arica');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('330','Colchane');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('324','Camarones');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('325','General Lagos');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('326','Putre');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('327','Alto Hospicio');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('328','Iquique');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('329','Camiña');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('331','Huara');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('332','Pica');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('333','Pozo Almonte');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('334','Antofagasta');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('335','Mejillones');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('336','Sierra Gorda');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('337','TalTal');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('338','Calama');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('339','Ollague');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('340','San Pedro de Atacama');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('341','María Elena');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('342','Tocopilla');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('343','Chañaral');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('344','Diego de Almagro');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('345','Caldera');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('346','Copiapo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('347','Tierra Amarilla');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('348','Alto del Camen');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('349','Freirina');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('350','Huasco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('351','Vallenar');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('352','Canela');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('353','Illapel');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('354','Los Vilos');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('355','Salamanca');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('356','Andacollo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('357','Coquimbo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('358','La Higuera');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('359','La Serena');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('360','Paihuaco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('361','Vicuña');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('362','Combarbalá');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('363','Monte Patria');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('364','Ovalle');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('365','Punitaqui');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('366','Río Hurtado');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('367','Isla de Pascua');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('368','Calle Larga');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('369','Los Andes');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('370','Rinconada');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('371','San Esteban');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('372','La Ligua');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('373','Papudo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('374','Petorca');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('375','Zapallar');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('376','Hijuelas');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('377','La Calera');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('378','La Cruz');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('379','Limache');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('380','Nogales');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('381','Olmué');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('382','Quillota');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('383','Algarrobo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('384','Cartagena');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('385','El Quisco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('386','El Tabo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('387','San Antonio');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('388','Santo Domingo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('389','Catemu');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('390','Llaillay');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('391','Panquehue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('392','Putaendo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('393','San Felipe');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('394','Santa Maria');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('395','casablanca');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('396','COncón');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('397','Juan Fernández');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('398','Puchuncaví');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('399','Quilpué');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('400','Quintero');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('401','Valparaiso');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('402','Villa Alemana');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('403','Viña del Mar');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('404','Colina');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('405','Lampa');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('406','TilTil');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('407','Pirque');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('408','Puente Alto');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('409','San José de Maipo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('410','Buin');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('411','Calera de Tango');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('412','Paine');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('413','San Bernardo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('414','Alhué');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('415','Curucaví');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('416','María Pinto');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('417','Melipilla');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('418','San Pedro');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('419','Cerrillos');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('420','Cerro Navia');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('421','Conchalí');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('422','El Bosque');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('423','Estación Central');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('424','Huechuraba');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('425','Independencia');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('426','La Cisterna');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('427','La Granja');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('428','La Florida');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('429','La Pintana');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('430','La Reina');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('431','Las Condes');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('432','Lo Barnechea');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('433','Lo Espejo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('434','Lo Prado');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('435','Macul');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('436','Maipú');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('437','Ñuñoa');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('438','Pedro Aguire Cerda');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('439','Peñalolén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('440','Providencia');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('441','Pudahuel');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('442','Quilicura');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('443','Quinta Normal');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('444','Recoleta');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('445','Renca');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('446','San Miguel');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('447','San Ramón');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('448','Santiago');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('449','Vitacura');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('450','El Monte');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('451','Isla de Maipo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('452','Padre Hurtado');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('453','Peñaflor');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('454','Talagante');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('455','Codegua');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('456','Coínco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('457','Coltauco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('458','Doñihue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('459','Graneros');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('460','Las Cabras');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('461','Machalí');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('462','Malloa');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('463','Mostazal');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('464','Olivar');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('465','Peumo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('466','Pichidegua');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('467','Quinta de Tilcoco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('468','Rancagua');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('469','Rengo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('470','Requínoa');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('471','San Vicente de Tagua Tagua');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('472','La Estrella');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('473','Litueche');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('474','Marchihue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('475','Navidad');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('476','Peredones');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('477','Pichilemu');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('478','Chépica');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('479','Chimbarongo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('480','Lolol');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('481','Nancagua');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('482','Palmilla');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('483','Peralillo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('484','Placilla');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('485','Pumanque');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('486','San Fernando');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('487','Santa Cruz');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('488','Cauquenes');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('489','Chanco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('490','Pelluhue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('491','Curicó');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('492','Hualañe');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('493','Licantén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('494','Molina');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('495','Rauco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('496','Romeral');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('497','Sagrada Familia');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('498','Teno');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('499','Vichulquén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('500','Colbún');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('501','Linares');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('502','Longaví');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('503','Parral');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('504','Retiro');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('505','San Javier');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('506','Villa Alegre');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('507','Yerbas Buenas');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('508','Constitución');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('509','Curepto');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('510','Empedrado');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('511','Maule');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('512','Pelarco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('513','Pencahue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('514','Río Claro');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('515','San Clemente');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('516','San Rafael');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('517','Talca');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('518','Arauco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('519','Cañete');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('520','Contulmo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('521','Curanilahue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('522','Lebu');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('523','Los Álamos');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('524','Tirúa');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('525','Alto Biobío');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('526','Antuco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('527','Cabrero');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('528','Laja');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('529','Los Ángeles');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('530','Mulchén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('531','Negrete');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('532','Quilaco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('533','Quilleco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('534','San Rosendo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('535','Santa Bárbara');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('536','Tucapel');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('537','Yumbel');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('538','Chiguayante');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('539','Concepción');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('540','Coronel');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('541','Nacimiento');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('542','Florida');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('543','Hualpén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('544','Hualqui');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('545','Lota');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('546','Penco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('547','San Pedro de la Paz');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('548','Santa Juana');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('549','Talcahuano');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('550','Tomé');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('551','Bulnes');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('552','Chillan');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('553','Chillan Viejo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('554','Cobquecura');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('555','Coelemu');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('556','Coihueco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('557','El Carmen');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('558','Ninhue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('559','Ñiquen');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('560','Pemuco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('561','Pinto');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('562','Portezuelo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('563','Quillón');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('564','Quirihue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('565','Ránquil');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('566','San Carlos');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('567','San Fabián');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('568','San Ignacio');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('569','San Nicolás');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('570','Treguaco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('571','Yungay');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('572','Carahue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('573','Cholchol');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('574','Cunco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('575','Curarrehue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('576','Freire');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('577','Galvarino');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('578','Gorbea');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('579','Lautaro');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('580','Loncoche');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('581','Melipeuco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('582','Nueva Imperial');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('583','Padre Las Casas');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('584','Perquenco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('585','Pitrufquén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('586','Pucón');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('587','Saavedra');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('588','Temuco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('589','Teodoro Schmidt');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('590','Toltén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('591','Vilcún');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('592','Villarrica');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('593','Angol');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('594','Collipulli');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('595','Curacautín');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('596','Ercilla');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('597','Lonquimay');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('598','Los Saunces');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('599','Lumaco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('600','Purén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('601','Renaico');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('602','Traiguén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('603','Victoria');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('604','Corral');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('605','Lanco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('606','Los Lagos');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('607','Máfil');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('608','Mariquina');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('609','Paillaco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('610','Panquipulli');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('611','Valdivia');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('612','Futrono');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('613','La Unión');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('614','Lago Ranco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('615','Río Bueno');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('616','Ancud');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('617','Castro');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('618','Chonchi');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('619','Curaco de Vélez');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('620','Dalcahue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('621','Puqueldón');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('622','Queilén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('623','Quemchi');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('624','Quellón');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('625','Quinchao');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('626','Calbuco');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('627','Cochamó');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('628','Fresia');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('629','Frutillar');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('630','Llanquihue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('631','Los Muermos');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('632','Maullín');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('633','Puerto Montt');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('634','Puerto Varas');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('635','Osorno');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('636','Puerto Octay');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('637','Purranque');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('638','Puyehue');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('639','Río Negro');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('640','San Juan de la Costa');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('641','San Pablo');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('642','Chaitén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('643','Futaleufú');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('644','Hualaihué');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('645','Palena');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('646','Aisén');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('647','Cisnes');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('648','Guaitecas');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('649','Cochrane');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('650','O''higgins');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('651','Tortel');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('652','Coihaique');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('653','Lago Verde');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('654','Chile Chico');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('655','Río Ibañez');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('656','Antartica');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('657','Cabo de Hornos');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('658','Laguna Blanca');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('659','Punta Arenas');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('660','Río Verde');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('661','San Gregorio');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('662','Porvenir');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('663','Primavera');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('664','Timaukel');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('665','Natales');
Insert into PORTAFOLIO.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('666','Torres del Paine');
REM INSERTING into PORTAFOLIO.RESERVA
SET DEFINE OFF;
Insert into PORTAFOLIO.RESERVA (ID_RESERVA,FECHA_RESERVA,CANTIDAD_PERSONAS,FECHA_SALIDA,RUT,ID_DEPARTAMENTO) values ('861','2019-11-23','5','2019-11-24','19039431-k','63');
Insert into PORTAFOLIO.RESERVA (ID_RESERVA,FECHA_RESERVA,CANTIDAD_PERSONAS,FECHA_SALIDA,RUT,ID_DEPARTAMENTO) values ('841','2019-11-21','5','2019-11-23','18213561-5','43');
Insert into PORTAFOLIO.RESERVA (ID_RESERVA,FECHA_RESERVA,CANTIDAD_PERSONAS,FECHA_SALIDA,RUT,ID_DEPARTAMENTO) values ('882','2019-11-25','3','2019-11-27','18213561-5','2');
Insert into PORTAFOLIO.RESERVA (ID_RESERVA,FECHA_RESERVA,CANTIDAD_PERSONAS,FECHA_SALIDA,RUT,ID_DEPARTAMENTO) values ('825','2019-11-14','5','2019-11-15','18213561-5','2');
REM INSERTING into PORTAFOLIO.ROL
SET DEFINE OFF;
Insert into PORTAFOLIO.ROL (ID_ROL,DESCRIPCION) values ('1','Administrador');
Insert into PORTAFOLIO.ROL (ID_ROL,DESCRIPCION) values ('2','Funcionario');
Insert into PORTAFOLIO.ROL (ID_ROL,DESCRIPCION) values ('3','Cliente');
REM INSERTING into PORTAFOLIO.SERVICIOS
SET DEFINE OFF;
Insert into PORTAFOLIO.SERVICIOS (ID_SRV,NOMBRE_SRV,PRECIO,ID_DEPARTAMENTO) values ('1','Netflix','19850','2');
Insert into PORTAFOLIO.SERVICIOS (ID_SRV,NOMBRE_SRV,PRECIO,ID_DEPARTAMENTO) values ('41','Gimancio','15000','43');
Insert into PORTAFOLIO.SERVICIOS (ID_SRV,NOMBRE_SRV,PRECIO,ID_DEPARTAMENTO) values ('21','Netflix','5500','43');
REM INSERTING into PORTAFOLIO.USUARIOS
SET DEFINE OFF;
Insert into PORTAFOLIO.USUARIOS (ID_USUARIO,RUT,NOMBRE,CORREO,TELEFONO,CLAVE,ID_ROL) values ('302','1-9','Renzo Espeleta','renzo.espeleta@gmail.com','956788856','123','2');
Insert into PORTAFOLIO.USUARIOS (ID_USUARIO,RUT,NOMBRE,CORREO,TELEFONO,CLAVE,ID_ROL) values ('249','19039431-k','Matias Quezada','mat.quezada@alumnos.duoc.cl','985457796','123','3');
Insert into PORTAFOLIO.USUARIOS (ID_USUARIO,RUT,NOMBRE,CORREO,TELEFONO,CLAVE,ID_ROL) values ('242','18213561-5','Manuel Torres','alejandro.torresolivos@gmail.com','931378869','123','1');
Insert into PORTAFOLIO.USUARIOS (ID_USUARIO,RUT,NOMBRE,CORREO,TELEFONO,CLAVE,ID_ROL) values ('322','1-7','Roberto Gonzalez','rober.gonzalez@alumnos.duoc.cl','956788854','123','3');
Insert into PORTAFOLIO.USUARIOS (ID_USUARIO,RUT,NOMBRE,CORREO,TELEFONO,CLAVE,ID_ROL) values ('343','1111111-1','Cliente de prueba','cliente@gmail.com','931378878','123','3');
--------------------------------------------------------
--  DDL for Index LOCALIDADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."LOCALIDADES_PK" ON "PORTAFOLIO"."LOCALIDADES" ("NOMBRE_LOCALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."USUARIOS_PK" ON "PORTAFOLIO"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPARTAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."DEPARTAMENTO_PK" ON "PORTAFOLIO"."DEPARTAMENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SERVICIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."SERVICIOS_PK" ON "PORTAFOLIO"."SERVICIOS" ("ID_SRV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger INSERTAR_CATEGORIA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."INSERTAR_CATEGORIA" 
   before insert on "PORTAFOLIO"."CATEGORIA" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select SEQ_ID_INVENTARIO.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."INSERTAR_CATEGORIA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERTAR_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."INSERTAR_USUARIOS" 
before insert on usuarios
for each row
begin
select inserta_usuario.nextval into :new.id_usuario from dual;
end;
/
ALTER TRIGGER "PORTAFOLIO"."INSERTAR_USUARIOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVOCHECKIN
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVOCHECKIN" 
   before insert on "PORTAFOLIO"."CHECKIN" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_CHECKIN" is null then 
         select SEQ_CHECK_IN.nextval into :NEW."ID_CHECKIN" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVOCHECKIN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVODEPARTAMENTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVODEPARTAMENTO" 
   before insert on "PORTAFOLIO"."DEPARTAMENTO" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select SEQ_ID_DEPARTAMENTO.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVODEPARTAMENTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVOINVENTARIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVOINVENTARIO" 
   before insert on "PORTAFOLIO"."INVENTARIO" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_INV" is null then 
         select SEQ_ID_INVENTARIO.nextval into :NEW."ID_INV" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "PORTAFOLIO"."NUEVOINVENTARIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVO_SERVICIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVO_SERVICIO" 
   before insert on "PORTAFOLIO"."SERVICIOS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_SRV" is null then 
         select USUARIO_SEQUENCIA.nextval into :NEW."ID_SRV" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVO_SERVICIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PORTAFOLIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."PORTAFOLIO" 
   before insert on "PORTAFOLIO"."RESERVA" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_RESERVA" is null then 
         select DEMO_CUST_SEQ.nextval into :NEW."ID_RESERVA" from dual; 
      end if; 
   end if; 
end;


/
ALTER TRIGGER "PORTAFOLIO"."PORTAFOLIO" ENABLE;
--------------------------------------------------------
--  DDL for Procedure P_CREAR_DEPARTAMENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CREAR_DEPARTAMENTO" 
(v_nombre varchar, v_ubicacion varchar, v_banos varchar, v_habitaciones varchar, v_valorarriendo float, v_descripcion varchar,v_fecha varchar,v_direccion varchar)
IS
begin
  insert into departamento
  values(v_nombre,v_ubicacion,v_banos,v_habitaciones,v_valorarriendo,v_descripcion,v_fecha,v_direccion);
end;

/
--------------------------------------------------------
--  DDL for Procedure P_CREAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CREAR_USUARIO" 
(v_rut varchar, v_nombre varchar, v_apellido varchar, v_correo varchar, v_pass varchar, rol number)
IS
v_id number;
begin
  insert into usuario
  values(0,v_rut,v_nombre,v_apellido,v_correo,v_pass);

  select max(id_usuario) into v_id
  from usuario;

  insert into roles_usuarios
  values(v_id,rol);
  dbms_output.put_line('MAX ID:  '||v_id);
end;



/
--------------------------------------------------------
--  DDL for Procedure P_ELIMINAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_ELIMINAR_USUARIO" 
(v_id number)
IS

begin
delete from roles_usuarios
  where ID_USUARIO = v_id;

  delete from usuario
  where ID_USUARIO=v_id;
  dbms_output.put_line(v_id||' Eliminado con exito');
end;



/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_CLIENTES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_CLIENTES" 
(
p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
Select a.id_usuario as id, c.descripcion as rol , a.rut_usuario as rut, a.nombre as nombre, 
a.apellido as apellido, a.correo as correo, a.pass as pass
from usuario a join roles_usuarios b on(a.id_usuario=b.id_usuario) join roles c using(id_rol)
WHERE c.descripcion='Cliente';

END P_LISTAR_CLIENTES;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_USUARIOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_USUARIOS" 
(
p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
Select a.id_usuario as id, c.descripcion as rol , a.rut_usuario as rut, a.nombre as nombre, 
a.apellido as apellido, a.correo as correo, a.pass as pass
from usuario a join roles_usuarios b on(a.id_usuario=b.id_usuario) join roles c using(id_rol)
WHERE c.descripcion IN ('Administrador','Funcionario');

END P_LISTAR_USUARIOS;

/
--------------------------------------------------------
--  DDL for Procedure P_MODIFICAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_MODIFICAR_USUARIO" 
(v_rut varchar, v_nombre varchar, v_apellido varchar, v_correo varchar, v_pass varchar)
IS

begin
  update usuario set nombre=v_nombre, apellido=v_apellido, correo=v_correo, pass=v_pass
  where rut_usuario= v_rut;
end;

/
--------------------------------------------------------
--  DDL for Procedure P_REGISTRA_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_REGISTRA_CLIENTE" 
(v_rut varchar, v_nombre varchar,v_correo varchar,v_fono varchar, v_pass varchar)
AS
  v_id number;
  err_num number;
  err_msg varchar2(1000);
begin


  insert into usuarios
  values(0,v_rut,v_nombre,v_correo,v_fono,v_pass);

  select max(id_usuario) into v_id
  from usuarios;






 exception
  WHEN OTHERS THEN

  err_num := SQLCODE;
  err_msg := SQLERRM;
  DBMS_OUTPUT.put_line('Error:'||TO_CHAR(err_num));
  DBMS_OUTPUT.put_line(err_msg);
end;

/
--------------------------------------------------------
--  DDL for Procedure P_REGISTRAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_REGISTRAR_CLIENTE" 
(v_rut varchar, v_nombre varchar, v_apellido varchar, v_correo varchar, v_pass varchar)
AS
  v_id number;
  err_num number;
  err_msg varchar2(1000);
begin


  insert into usuario
  values(0,v_rut,v_nombre,v_apellido,v_correo,v_pass);

  select max(id_usuario) into v_id
  from usuario;

  insert into roles_usuarios
  values(v_id,5);




 exception
  WHEN OTHERS THEN

  err_num := SQLCODE;
  err_msg := SQLERRM;
  DBMS_OUTPUT.put_line('Error:'||TO_CHAR(err_num));
  DBMS_OUTPUT.put_line(err_msg);
end;


/
--------------------------------------------------------
--  DDL for Package TYPES
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PORTAFOLIO"."TYPES" 
AS
type cursorType is ref cursor;
END;



/
--------------------------------------------------------
--  DDL for Function ACCESO_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PORTAFOLIO"."ACCESO_USUARIO" (p_rut usuarios.rut %type,p_contrasena usuarios.clave %type)return integer is

p_rut_bd usuarios.rut %type;
p_contrasena_bd usuarios.clave %type;
 BEGIN
select rut, clave into p_rut_bd, p_contrasena_bd from usuarios where rut = p_rut and clave = p_contrasena;
if p_contrasena = p_contrasena_bd and p_rut = p_rut_bd then
 return 1;
 else
 return 0;
 end if;
 exception 
 when NO_DATA_FOUND THEN
 RETURN 0;
 END;

/
--------------------------------------------------------
--  DDL for Function F_RETORNA_NOMBRE
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PORTAFOLIO"."F_RETORNA_NOMBRE" 
(v_correo IN varchar) return varchar 
IS
  v_nombre varchar(200);
BEGIN
  select nombre  into v_nombre
  from usuarios
  where CORREO = v_correo;
  return(v_nombre);
END f_retorna_nombre;

/
--------------------------------------------------------
--  DDL for Function F_RETORNAR_NOMBRE
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PORTAFOLIO"."F_RETORNAR_NOMBRE" 
(v_correo IN varchar) return varchar 
IS
  v_nombre varchar(100);
  v_apellido varchar(100);
BEGIN
  select nombre || ' ' || apellido into v_nombre
  from usuario
  where CORREO = v_correo;
  return(v_nombre);
END f_retornar_nombre;


/
--------------------------------------------------------
--  DDL for Function F_RETORNAR_RUT
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PORTAFOLIO"."F_RETORNAR_RUT" 
(v_correo IN varchar) return varchar 
IS
  v_rut varchar(20);
BEGIN
  select rut_usuario into v_rut
  from usuario
  where CORREO = v_correo;
  return(v_rut);
END f_retornar_rut;



/
--------------------------------------------------------
--  DDL for Function F_RETORNA_RUT
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PORTAFOLIO"."F_RETORNA_RUT" 
(v_correo IN varchar) return varchar 
IS
  v_rut varchar(20);
BEGIN
  select rut into v_rut
  from usuarios
  where CORREO = v_correo;
  return(v_rut);
END f_retorna_rut;

/
--------------------------------------------------------
--  DDL for Function LOGIN_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PORTAFOLIO"."LOGIN_USUARIO" (p_rut usuario.rut %type,p_contrasena usuario.contrasena %type)return integer is

p_rut_bd usuario.rut %type;
p_contrasena_bd usuario.contrasena %type;
 BEGIN
select rut, contrasena into p_rut_bd, p_contrasena_bd from usuario where rut = p_rut and contrasena = p_contrasena;
if p_contrasena = p_contrasena_bd and p_rut = p_rut_bd then
 return 1;
 else
 return 0;
 end if;
 exception 
 when NO_DATA_FOUND THEN
 RETURN 0;
 END;



/
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."ROL" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."DEPARTAMENTO" ADD CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."DEPARTAMENTO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICIOS
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."SERVICIOS" ADD CONSTRAINT "SERVICIOS_PK" PRIMARY KEY ("ID_SRV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."SERVICIOS" MODIFY ("ID_SRV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCALIDADES
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."LOCALIDADES" ADD CONSTRAINT "LOCALIDADES_PK" PRIMARY KEY ("NOMBRE_LOCALIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."LOCALIDADES" MODIFY ("NOMBRE_LOCALIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."USUARIOS" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."USUARIOS" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIOS" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIOS" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIOS" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVENTARIO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."INVENTARIO" MODIFY ("ESTADO" NOT NULL ENABLE);
