--------------------------------------------------------
-- Archivo creado  - jueves-octubre-10-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 681 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INSERTA_ADMIN
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."INSERTA_ADMIN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INSERTA_AGENDA
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."INSERTA_AGENDA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INSERTA_COTIZACION
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."INSERTA_COTIZACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INSERTA_EDIFICIO
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."INSERTA_EDIFICIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INSERTA_MATERIAL
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."INSERTA_MATERIAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INSERTA_PAQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."INSERTA_PAQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INSERTA_TMATERIAL
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."INSERTA_TMATERIAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INSERTA_TPAQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."INSERTA_TPAQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INSERTA_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."INSERTA_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SECUENCIA_ID_BOLETA
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SECUENCIA_ID_BOLETA"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_AGENDAR
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_AGENDAR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ATENCION
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_ATENCION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CIERRE_ORDEN
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_CIERRE_ORDEN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DAR_AVISO
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_DAR_AVISO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DERIVAR
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_DERIVAR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ESPECIALIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_ESPECIALIDAD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FICHA_MEDICA
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_FICHA_MEDICA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_HISTORIAL_MEDICO
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_HISTORIAL_MEDICO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_HORARIO
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_HORARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_AGREGAR
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_ID_AGREGAR"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_IDATENCION
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_IDATENCION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_IDNOTA
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_IDNOTA"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_IDPAGO
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_IDPAGO"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_PAGO_HONORARIOS
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_ID_PAGO_HONORARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PACIENTE
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_PACIENTE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PERSONAL
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_PERSONAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REGISTRARSE_PREVISION
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_REGISTRARSE_PREVISION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TIPOS_ATENCIONES
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SEQ_TIPOS_ATENCIONES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIO_SEQUENCIA
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."USUARIO_SEQUENCIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."DEPARTAMENTO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(300 BYTE), 
	"UBICACION" VARCHAR2(300 BYTE), 
	"BANOS" VARCHAR2(20 BYTE), 
	"HABITACIONES" VARCHAR2(20 BYTE), 
	"VALORARRIENDO" FLOAT(126), 
	"DESCRIPCION" VARCHAR2(600 BYTE), 
	"FECHA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVENTARIO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."INVENTARIO" 
   (	"ID_INV" NUMBER, 
	"ID_DEPTO" VARCHAR2(20 BYTE), 
	"PRODUCTO" VARCHAR2(300 BYTE), 
	"CANTIDAD" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(700 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCALIDADES
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."LOCALIDADES" 
   (	"ID_LOCALIDAD" NUMBER, 
	"NOMBRE_LOCALIDAD" VARCHAR2(700 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVA
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."RESERVA" 
   (	"ID_RESERVA" NUMBER(10,0), 
	"FECHA_RESERVA" VARCHAR2(60 BYTE), 
	"CANTIDAD_PERSONAS" VARCHAR2(10 BYTE), 
	"FECHA_SALIDA" VARCHAR2(60 BYTE), 
	"RUT" VARCHAR2(20 BYTE), 
	"ID_DEPARTAMENTO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."ROLES" 
   (	"ID_ROL" NUMBER, 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"VIGENTE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES_USUARIOS
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."ROLES_USUARIOS" 
   (	"ID_USUARIO" NUMBER, 
	"ID_ROL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."USUARIO" 
   (	"ID_USUARIO" NUMBER, 
	"RUT_USUARIO" VARCHAR2(15 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"CORREO" VARCHAR2(100 BYTE), 
	"PASS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PRUEBA.DEPARTAMENTO
SET DEFINE OFF;
Insert into PRUEBA.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA) values ('21','Edificio nogales','Talca      ','1','1','4500','otra ves','2019-09-30');
Insert into PRUEBA.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA) values ('22','Edificio miraflores','Valparaiso      ','2','2','4500000','prueba edicion','2019-09-30');
Insert into PRUEBA.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA) values ('32','Arriendo ','Valparaiso','1','1','45000','<p>prueba</p>','2019-10-03');
Insert into PRUEBA.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA) values ('309','Edificio San Carlos','Santiago','2','2','340000','<p>En arriendo</p>
','2019-10-08');
Insert into PRUEBA.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA) values ('61','Edificio costa azul','Puerto Varas','3','4','250000','<p>En arriendo</p>
','2019-10-06');
REM INSERTING into PRUEBA.INVENTARIO
SET DEFINE OFF;
Insert into PRUEBA.INVENTARIO (ID_INV,ID_DEPTO,PRODUCTO,CANTIDAD,ESTADO,DESCRIPCION) values ('26','21','notebook','1','bueno','bueno');
Insert into PRUEBA.INVENTARIO (ID_INV,ID_DEPTO,PRODUCTO,CANTIDAD,ESTADO,DESCRIPCION) values ('27','21','prueba','1','bueno','bueno');
Insert into PRUEBA.INVENTARIO (ID_INV,ID_DEPTO,PRODUCTO,CANTIDAD,ESTADO,DESCRIPCION) values ('28','21','PRUEBAS DE CARGA 4533','1','1',null);
Insert into PRUEBA.INVENTARIO (ID_INV,ID_DEPTO,PRODUCTO,CANTIDAD,ESTADO,DESCRIPCION) values ('44','22','Velador','2','Bonito','Pollito al velador');
Insert into PRUEBA.INVENTARIO (ID_INV,ID_DEPTO,PRODUCTO,CANTIDAD,ESTADO,DESCRIPCION) values ('1','21','HOLA','1','BUENO','PRUEBA');
REM INSERTING into PRUEBA.LOCALIDADES
SET DEFINE OFF;
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('323','Arica');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('330','Colchane');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('324','Camarones');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('325','General Lagos');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('326','Putre');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('327','Alto Hospicio');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('328','Iquique');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('329','Camiña');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('331','Huara');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('332','Pica');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('333','Pozo Almonte');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('334','Antofagasta');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('335','Mejillones');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('336','Sierra Gorda');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('337','TalTal');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('338','Calama');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('339','Ollague');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('340','San Pedro de Atacama');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('341','María Elena');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('342','Tocopilla');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('343','Chañaral');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('344','Diego de Almagro');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('345','Caldera');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('346','Copiapo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('347','Tierra Amarilla');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('348','Alto del Camen');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('349','Freirina');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('350','Huasco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('351','Vallenar');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('352','Canela');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('353','Illapel');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('354','Los Vilos');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('355','Salamanca');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('356','Andacollo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('357','Coquimbo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('358','La Higuera');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('359','La Serena');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('360','Paihuaco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('361','Vicuña');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('362','Combarbalá');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('363','Monte Patria');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('364','Ovalle');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('365','Punitaqui');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('366','Río Hurtado');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('367','Isla de Pascua');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('368','Calle Larga');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('369','Los Andes');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('370','Rinconada');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('371','San Esteban');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('372','La Ligua');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('373','Papudo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('374','Petorca');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('375','Zapallar');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('376','Hijuelas');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('377','La Calera');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('378','La Cruz');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('379','Limache');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('380','Nogales');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('381','Olmué');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('382','Quillota');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('383','Algarrobo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('384','Cartagena');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('385','El Quisco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('386','El Tabo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('387','San Antonio');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('388','Santo Domingo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('389','Catemu');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('390','Llaillay');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('391','Panquehue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('392','Putaendo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('393','San Felipe');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('394','Santa Maria');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('395','casablanca');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('396','COncón');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('397','Juan Fernández');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('398','Puchuncaví');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('399','Quilpué');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('400','Quintero');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('401','Valparaíso');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('402','Villa Alemana');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('403','Viña del Mar');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('404','Colina');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('405','Lampa');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('406','TilTil');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('407','Pirque');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('408','Puente Alto');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('409','San José de Maipo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('410','Buin');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('411','Calera de Tango');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('412','Paine');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('413','San Bernardo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('414','Alhué');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('415','Curucaví');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('416','María Pinto');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('417','Melipilla');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('418','San Pedro');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('419','Cerrillos');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('420','Cerro Navia');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('421','Conchalí');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('422','El Bosque');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('423','Estación Central');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('424','Huechuraba');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('425','Independencia');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('426','La Cisterna');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('427','La Granja');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('428','La Florida');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('429','La Pintana');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('430','La Reina');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('431','Las Condes');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('432','Lo Barnechea');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('433','Lo Espejo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('434','Lo Prado');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('435','Macul');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('436','Maipú');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('437','Ñuñoa');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('438','Pedro Aguire Cerda');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('439','Peñalolén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('440','Providencia');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('441','Pudahuel');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('442','Quilicura');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('443','Quinta Normal');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('444','Recoleta');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('445','Renca');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('446','San Miguel');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('447','San Ramón');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('448','Santiago');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('449','Vitacura');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('450','El Monte');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('451','Isla de Maipo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('452','Padre Hurtado');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('453','Peñaflor');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('454','Talagante');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('455','Codegua');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('456','Coínco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('457','Coltauco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('458','Doñihue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('459','Graneros');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('460','Las Cabras');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('461','Machalí');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('462','Malloa');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('463','Mostazal');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('464','Olivar');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('465','Peumo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('466','Pichidegua');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('467','Quinta de Tilcoco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('468','Rancagua');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('469','Rengo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('470','Requínoa');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('471','San Vicente de Tagua Tagua');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('472','La Estrella');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('473','Litueche');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('474','Marchihue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('475','Navidad');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('476','Peredones');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('477','Pichilemu');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('478','Chépica');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('479','Chimbarongo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('480','Lolol');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('481','Nancagua');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('482','Palmilla');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('483','Peralillo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('484','Placilla');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('485','Pumanque');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('486','San Fernando');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('487','Santa Cruz');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('488','Cauquenes');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('489','Chanco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('490','Pelluhue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('491','Curicó');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('492','Hualañe');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('493','Licantén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('494','Molina');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('495','Rauco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('496','Romeral');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('497','Sagrada Familia');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('498','Teno');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('499','Vichulquén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('500','Colbún');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('501','Linares');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('502','Longaví');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('503','Parral');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('504','Retiro');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('505','San Javier');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('506','Villa Alegre');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('507','Yerbas Buenas');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('508','Constitución');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('509','Curepto');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('510','Empedrado');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('511','Maule');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('512','Pelarco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('513','Pencahue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('514','Río Claro');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('515','San Clemente');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('516','San Rafael');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('517','Talca');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('518','Arauco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('519','Cañete');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('520','Contulmo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('521','Curanilahue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('522','Lebu');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('523','Los Álamos');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('524','Tirúa');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('525','Alto Biobío');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('526','Antuco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('527','Cabrero');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('528','Laja');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('529','Los Ángeles');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('530','Mulchén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('531','Negrete');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('532','Quilaco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('533','Quilleco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('534','San Rosendo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('535','Santa Bárbara');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('536','Tucapel');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('537','Yumbel');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('538','Chiguayante');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('539','Concepción');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('540','Coronel');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('541','Nacimiento');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('542','Florida');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('543','Hualpén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('544','Hualqui');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('545','Lota');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('546','Penco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('547','San Pedro de la Paz');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('548','Santa Juana');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('549','Talcahuano');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('550','Tomé');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('551','Bulnes');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('552','Chillan');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('553','Chillan Viejo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('554','Cobquecura');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('555','Coelemu');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('556','Coihueco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('557','El Carmen');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('558','Ninhue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('559','Ñiquen');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('560','Pemuco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('561','Pinto');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('562','Portezuelo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('563','Quillón');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('564','Quirihue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('565','Ránquil');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('566','San Carlos');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('567','San Fabián');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('568','San Ignacio');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('569','San Nicolás');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('570','Treguaco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('571','Yungay');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('572','Carahue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('573','Cholchol');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('574','Cunco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('575','Curarrehue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('576','Freire');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('577','Galvarino');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('578','Gorbea');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('579','Lautaro');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('580','Loncoche');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('581','Melipeuco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('582','Nueva Imperial');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('583','Padre Las Casas');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('584','Perquenco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('585','Pitrufquén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('586','Pucón');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('587','Saavedra');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('588','Temuco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('589','Teodoro Schmidt');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('590','Toltén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('591','Vilcún');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('592','Villarrica');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('593','Angol');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('594','Collipulli');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('595','Curacautín');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('596','Ercilla');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('597','Lonquimay');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('598','Los Saunces');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('599','Lumaco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('600','Purén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('601','Renaico');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('602','Traiguén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('603','Victoria');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('604','Corral');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('605','Lanco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('606','Los Lagos');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('607','Máfil');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('608','Mariquina');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('609','Paillaco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('610','Panquipulli');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('611','Valdivia');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('612','Futrono');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('613','La Unión');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('614','Lago Ranco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('615','Río Bueno');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('616','Ancud');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('617','Castro');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('618','Chonchi');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('619','Curaco de Vélez');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('620','Dalcahue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('621','Puqueldón');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('622','Queilén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('623','Quemchi');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('624','Quellón');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('625','Quinchao');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('626','Calbuco');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('627','Cochamó');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('628','Fresia');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('629','Frutillar');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('630','Llanquihue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('631','Los Muermos');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('632','Maullín');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('633','Puerto Montt');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('634','Puerto Varas');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('635','Osorno');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('636','Puerto Octay');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('637','Purranque');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('638','Puyehue');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('639','Río Negro');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('640','San Juan de la Costa');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('641','San Pablo');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('642','Chaitén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('643','Futaleufú');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('644','Hualaihué');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('645','Palena');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('646','Aisén');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('647','Cisnes');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('648','Guaitecas');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('649','Cochrane');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('650','O''higgins');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('651','Tortel');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('652','Coihaique');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('653','Lago Verde');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('654','Chile Chico');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('655','Río Ibañez');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('656','Antártica');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('657','Cabo de Hornos');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('658','Laguna Blanca');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('659','Punta Arenas');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('660','Río Verde');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('661','San Gregorio');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('662','Porvenir');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('663','Primavera');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('664','Timaukel');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('665','Natales');
Insert into PRUEBA.LOCALIDADES (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('666','Torres del Paine');
REM INSERTING into PRUEBA.RESERVA
SET DEFINE OFF;
Insert into PRUEBA.RESERVA (ID_RESERVA,FECHA_RESERVA,CANTIDAD_PERSONAS,FECHA_SALIDA,RUT,ID_DEPARTAMENTO) values ('24','2019-10-01','4','2019-10-19','18213561-5','21');
Insert into PRUEBA.RESERVA (ID_RESERVA,FECHA_RESERVA,CANTIDAD_PERSONAS,FECHA_SALIDA,RUT,ID_DEPARTAMENTO) values ('29','2019-10-04','4','2019-10-20','18213561-5','22');
Insert into PRUEBA.RESERVA (ID_RESERVA,FECHA_RESERVA,CANTIDAD_PERSONAS,FECHA_SALIDA,RUT,ID_DEPARTAMENTO) values ('31','2019-10-01','5','2019-10-27','18213561-5','22');
Insert into PRUEBA.RESERVA (ID_RESERVA,FECHA_RESERVA,CANTIDAD_PERSONAS,FECHA_SALIDA,RUT,ID_DEPARTAMENTO) values ('41','2019-10-01','4','2019-10-27','19039431-k','22');
Insert into PRUEBA.RESERVA (ID_RESERVA,FECHA_RESERVA,CANTIDAD_PERSONAS,FECHA_SALIDA,RUT,ID_DEPARTAMENTO) values ('43','2019-10-31','3','2019-11-02','19039431-k','22');
REM INSERTING into PRUEBA.ROLES
SET DEFINE OFF;
Insert into PRUEBA.ROLES (ID_ROL,DESCRIPCION,VIGENTE) values ('1','Administrador',null);
Insert into PRUEBA.ROLES (ID_ROL,DESCRIPCION,VIGENTE) values ('2','Funcionario',null);
Insert into PRUEBA.ROLES (ID_ROL,DESCRIPCION,VIGENTE) values ('5','Cliente',null);
REM INSERTING into PRUEBA.ROLES_USUARIOS
SET DEFINE OFF;
Insert into PRUEBA.ROLES_USUARIOS (ID_USUARIO,ID_ROL) values ('141','1');
Insert into PRUEBA.ROLES_USUARIOS (ID_USUARIO,ID_ROL) values ('161','1');
Insert into PRUEBA.ROLES_USUARIOS (ID_USUARIO,ID_ROL) values ('162','2');
Insert into PRUEBA.ROLES_USUARIOS (ID_USUARIO,ID_ROL) values ('163','5');
REM INSERTING into PRUEBA.USUARIO
SET DEFINE OFF;
Insert into PRUEBA.USUARIO (ID_USUARIO,RUT_USUARIO,NOMBRE,APELLIDO,CORREO,PASS) values ('141','18213561-5','Manuel','Torres','alejandro.torresolivos@gmail.com','123');
Insert into PRUEBA.USUARIO (ID_USUARIO,RUT_USUARIO,NOMBRE,APELLIDO,CORREO,PASS) values ('162','19084218-5','Renzo Crisitan','Espeleta','renzo.espeleta@gmail.com','123');
Insert into PRUEBA.USUARIO (ID_USUARIO,RUT_USUARIO,NOMBRE,APELLIDO,CORREO,PASS) values ('163','19039431-k','Matias','Quezada','mat.quezada@alumnos.duoc.cl','123');
Insert into PRUEBA.USUARIO (ID_USUARIO,RUT_USUARIO,NOMBRE,APELLIDO,CORREO,PASS) values ('161','18513856-9','Roberto alonso','Gonzalez','rober.gonzalez@alumnos.duoc.cl','123');
--------------------------------------------------------
--  DDL for Index ROLES_USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ROLES_USUARIOS_PK" ON "PRUEBA"."ROLES_USUARIOS" ("ID_USUARIO", "ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPARTAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."DEPARTAMENTO_PK" ON "PRUEBA"."DEPARTAMENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_USUARIO_CORREO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."UQ_USUARIO_CORREO" ON "PRUEBA"."USUARIO" ("CORREO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ROLES_PK" ON "PRUEBA"."ROLES" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_USUARIO_RUT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."UQ_USUARIO_RUT" ON "PRUEBA"."USUARIO" ("RUT_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."USUARIO_PK" ON "PRUEBA"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger INSERTAR_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."INSERTAR_USUARIO" 
before insert on usuario
for each row
begin
select inserta_usuario.nextval into :new.id_usuario from dual;
end;

/
ALTER TRIGGER "PRUEBA"."INSERTAR_USUARIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVALCOALIDAD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."NUEVALCOALIDAD" 
   before insert on "PRUEBA"."LOCALIDADES" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_LOCALIDAD" is null then 
         select DEMO_CUST_SEQ.nextval into :NEW."ID_LOCALIDAD" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PRUEBA"."NUEVALCOALIDAD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVALOCALIDAD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."NUEVALOCALIDAD" 
   before insert on "PRUEBA"."INVENTARIO" 
   for each row 
begin  
   if inserting then 
      if :NEW."" is null then 
         select .nextval into :NEW."" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PRUEBA"."NUEVALOCALIDAD" DISABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVODEPARTAMENTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."NUEVODEPARTAMENTO" 
   before insert on "PRUEBA"."DEPARTAMENTO" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select DEMO_CUST_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PRUEBA"."NUEVODEPARTAMENTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVOINVENTARIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."NUEVOINVENTARIO" 
   before insert on "PRUEBA"."INVENTARIO" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_INV" is null then 
         select DEMO_CUST_SEQ.nextval into :NEW."ID_INV" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PRUEBA"."NUEVOINVENTARIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRUEBA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."PRUEBA" 
   before insert on "PRUEBA"."RESERVA" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_RESERVA" is null then 
         select DEMO_CUST_SEQ.nextval into :NEW."ID_RESERVA" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PRUEBA"."PRUEBA" ENABLE;
--------------------------------------------------------
--  DDL for Procedure P_CREAR_DEPARTAMENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PRUEBA"."P_CREAR_DEPARTAMENTO" 
(v_nombre varchar, v_ubicacion varchar, v_banos varchar,v_habitaciones varchar,v_valorarriendo float,v_descripcion varchar,v_fecha varchar)
IS
v_id number;
begin
  insert into departamento
  values(0,v_nombre,v_ubicacion,v_banos,v_habitaciones,v_valorarriendo,v_descripcion,v_fecha);

  select max(id) into v_id
  from departamento;

  dbms_output.put_line('MAX ID:  '||v_id);
end;

/
--------------------------------------------------------
--  DDL for Procedure P_CREAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PRUEBA"."P_CREAR_USUARIO" 
(v_rut varchar, v_nombre varchar, v_apellido varchar, v_correo varchar, v_pass varchar, rol number)
IS
v_id number;
begin
  insert into usuario
  values(0,v_rut,v_nombre,v_apellido,v_correo,v_pass);

  select max(id_usuario) into v_id
  from usuario;

  insert into roles_usuarios
  values(v_id,rol);
  dbms_output.put_line('MAX ID:  '||v_id);
end;


/
--------------------------------------------------------
--  DDL for Procedure P_ELIMINAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PRUEBA"."P_ELIMINAR_USUARIO" 
(v_id number)
IS

begin
delete from roles_usuarios
  where ID_USUARIO = v_id;

  delete from usuario
  where ID_USUARIO=v_id;
  dbms_output.put_line(v_id||' Eliminado con exito');
end;


/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_SOLICITUDES_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PRUEBA"."P_LISTAR_SOLICITUDES_CLIENTE" 
(
 v_rutCliente varchar, p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
select id_reserva as id, fecha_reserva as fecha_sol
from RESERVA
where RUT=v_rutCliente
order by FECHA_RESERVA desc;

END p_listar_solicitudes_cliente;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_USUARIOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PRUEBA"."P_LISTAR_USUARIOS" 
(
p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
Select a.id_usuario as id, c.descripcion as rol , a.rut_usuario as rut, a.nombre as nombre, 
a.apellido as apellido, a.correo as correo, a.pass as pass
from usuario a join roles_usuarios b on(a.id_usuario=b.id_usuario) join roles c using(id_rol) order by a.id_usuario;

END p_listar_usuarios;


/
--------------------------------------------------------
--  DDL for Procedure P_MODIFICAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PRUEBA"."P_MODIFICAR_USUARIO" 
(v_rut varchar, v_nombre varchar, v_apellido varchar, v_correo varchar, v_pass varchar)
IS

begin
  update usuario set nombre=v_nombre, apellido=v_apellido, correo=v_correo, pass=v_pass
  where rut_usuario= v_rut;
end;


/
--------------------------------------------------------
--  DDL for Procedure P_REGISTRAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PRUEBA"."P_REGISTRAR_CLIENTE" 
(v_rut varchar, v_nombre varchar, v_apellido varchar, v_correo varchar, v_pass varchar)
AS
  v_id number;
  err_num number;
  err_msg varchar2(1000);
begin


  insert into usuario
  values(0,v_rut,v_nombre,v_apellido,v_correo,v_pass);

  select max(id_usuario) into v_id
  from usuario;

  insert into roles_usuarios
  values(v_id,5);




 exception
  WHEN OTHERS THEN

  err_num := SQLCODE;
  err_msg := SQLERRM;
  DBMS_OUTPUT.put_line('Error:'||TO_CHAR(err_num));
  DBMS_OUTPUT.put_line(err_msg);
end;

/
--------------------------------------------------------
--  DDL for Package TYPES
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PRUEBA"."TYPES" 
AS
type cursorType is ref cursor;
END;


/
--------------------------------------------------------
--  DDL for Function F_RETORNAR_NOMBRE
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PRUEBA"."F_RETORNAR_NOMBRE" 
(v_correo IN varchar) return varchar 
IS
  v_nombre varchar(100);
  v_apellido varchar(100);
BEGIN
  select nombre || ' ' || apellido into v_nombre
  from usuario
  where CORREO = v_correo;
  return(v_nombre);
END f_retornar_nombre;

/
--------------------------------------------------------
--  DDL for Function F_RETORNAR_RUT
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PRUEBA"."F_RETORNAR_RUT" 
(v_correo IN varchar) return varchar 
IS
  v_rut varchar(20);
BEGIN
  select rut_usuario into v_rut
  from usuario
  where CORREO = v_correo;
  return(v_rut);
END f_retornar_rut;


/
--------------------------------------------------------
--  DDL for Function LOGIN_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PRUEBA"."LOGIN_USUARIO" (p_rut usuario.rut %type,p_contrasena usuario.contrasena %type)return integer is

p_rut_bd usuario.rut %type;
p_contrasena_bd usuario.contrasena %type;
 BEGIN
select rut, contrasena into p_rut_bd, p_contrasena_bd from usuario where rut = p_rut and contrasena = p_contrasena;
if p_contrasena = p_contrasena_bd and p_rut = p_rut_bd then
 return 1;
 else
 return 0;
 end if;
 exception 
 when NO_DATA_FOUND THEN
 RETURN 0;
 END;


/
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."USUARIO" MODIFY ("RUT_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."USUARIO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."USUARIO" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."USUARIO" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."USUARIO" ADD CONSTRAINT "UQ_USUARIO_RUT" UNIQUE ("RUT_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."USUARIO" ADD CONSTRAINT "UQ_USUARIO_CORREO" UNIQUE ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVENTARIO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."INVENTARIO" MODIFY ("ESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."DEPARTAMENTO" MODIFY ("HABITACIONES" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."DEPARTAMENTO" MODIFY ("UBICACION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."DEPARTAMENTO" ADD CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."DEPARTAMENTO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES_USUARIOS
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ROLES_USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ROLES_USUARIOS" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ROLES_USUARIOS" ADD CONSTRAINT "ROLES_USUARIOS_PK" PRIMARY KEY ("ID_USUARIO", "ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ROLES" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ROLES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROLES_USUARIOS
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ROLES_USUARIOS" ADD CONSTRAINT "ROLES_USUARIOS_ROLES_FK" FOREIGN KEY ("ID_ROL")
	  REFERENCES "PRUEBA"."ROLES" ("ID_ROL") ENABLE;
  ALTER TABLE "PRUEBA"."ROLES_USUARIOS" ADD CONSTRAINT "ROLES_USUARIOS_USUARIO_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PRUEBA"."USUARIO" ("ID_USUARIO") ENABLE;
