--------------------------------------------------------
-- Archivo creado  - lunes-diciembre-02-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 901 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INSERTA_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."INSERTA_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 421 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CHECK_IN
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_CHECK_IN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CHECK_OUT
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_CHECK_OUT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONTRATAR_SERVICIOS
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_CONTRATAR_SERVICIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_DEPARTAMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_ID_DEPARTAMENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_INVENTARIO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_ID_INVENTARIO"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_IDPAGO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_IDPAGO"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_IDRESERVA
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_IDRESERVA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SERVICIO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_SERVICIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIO_SEQUENCIA
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."USUARIO_SEQUENCIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."CATEGORIA" 
   (	"CATEGORIA" VARCHAR2(100 BYTE), 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHECKIN
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."CHECKIN" 
   (	"ID_CHECKIN" NUMBER, 
	"FECHA_CHECKIN" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ID_RESERVA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHECKOUT
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."CHECKOUT" 
   (	"ID_CHECKOUT" NUMBER, 
	"FECHA_CHECKOUT" NVARCHAR2(30), 
	"DESCRIPCION" NVARCHAR2(500), 
	"ID_RESERVA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."DEPARTAMENTO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(300 BYTE), 
	"UBICACION" VARCHAR2(150 BYTE), 
	"BANOS" VARCHAR2(20 BYTE), 
	"HABITACIONES" VARCHAR2(20 BYTE), 
	"VALORARRIENDO" VARCHAR2(60 BYTE), 
	"DESCRIPCION" VARCHAR2(600 BYTE), 
	"FECHA" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(300 BYTE), 
	"HABILITADO" VARCHAR2(20 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVENTARIO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."INVENTARIO" 
   (	"ID_INV" NUMBER, 
	"ID_DEPTO" VARCHAR2(20 BYTE), 
	"PRODUCTO" VARCHAR2(128 BYTE), 
	"CANTIDAD" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(700 BYTE), 
	"CATEGORIA" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCALIDAD
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."LOCALIDAD" 
   (	"ID_LOCALIDAD" NUMBER, 
	"NOMBRE_LOCALIDAD" VARCHAR2(700 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLANIFICARTRANSPORTE
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."PLANIFICARTRANSPORTE" 
   (	"ID_PLANIFICACION" NUMBER, 
	"ID_SOLICITUD" VARCHAR2(20 BYTE), 
	"CONDUCTOR" VARCHAR2(100 BYTE), 
	"AUTO" VARCHAR2(100 BYTE), 
	"PATENTE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."RESERVA" 
   (	"ID_RESERVA" NUMBER(4,0), 
	"FECHA_RESERVA" VARCHAR2(60 BYTE), 
	"CANTIDAD_PERSONAS" VARCHAR2(60 BYTE), 
	"FECHA_SALIDA" VARCHAR2(60 BYTE), 
	"RUT" VARCHAR2(20 BYTE), 
	"ID_DEPARTAMENTO" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."ROL" 
   (	"ID_ROL" NUMBER, 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERV
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."SERV" 
   (	"ID_SERV" NUMBER, 
	"FECHA_CONTRATACION" VARCHAR2(50 BYTE), 
	"ID_SRV" VARCHAR2(20 BYTE), 
	"ID_RESERVA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICIO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."SERVICIO" 
   (	"ID_SRV" NUMBER, 
	"NOMBRE_SRV" VARCHAR2(800 BYTE), 
	"PRECIO" VARCHAR2(20 BYTE), 
	"ID_DEPARTAMENTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOLICITUDTRANSPORTE
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."SOLICITUDTRANSPORTE" 
   (	"ID_SOLICITUD" NUMBER, 
	"ID_RESERVA" VARCHAR2(20 BYTE), 
	"FECHA_SOLICITUD" VARCHAR2(20 BYTE), 
	"HORA_SOLICITUD" VARCHAR2(20 BYTE), 
	"ORIGEN" VARCHAR2(100 BYTE), 
	"DESTINO" VARCHAR2(100 BYTE), 
	"ESTADO" VARCHAR2(100 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."USUARIO" 
   (	"ID_USUARIO" NUMBER(4,0) DEFAULT NULL, 
	"RUT" VARCHAR2(15 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"CORREO" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(100 BYTE), 
	"CLAVE" VARCHAR2(20 BYTE), 
	"ID_ROL" NUMBER(4,0) DEFAULT 3
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PORTAFOLIO.CATEGORIA
SET DEFINE OFF;
Insert into PORTAFOLIO.CATEGORIA (CATEGORIA,ID) values ('Baño','63');
Insert into PORTAFOLIO.CATEGORIA (CATEGORIA,ID) values ('Cocina','64');
Insert into PORTAFOLIO.CATEGORIA (CATEGORIA,ID) values ('Muebleria','61');
Insert into PORTAFOLIO.CATEGORIA (CATEGORIA,ID) values ('Electrodomestico','62');
REM INSERTING into PORTAFOLIO.CHECKIN
SET DEFINE OFF;
Insert into PORTAFOLIO.CHECKIN (ID_CHECKIN,FECHA_CHECKIN,DESCRIPCION,ID_RESERVA) values ('23','2019-11-29','                                                                                      
  El sr ha iniciado su estadia en el hotel  a las 14:30 horas del 28 de noviembre 2019 .                                         
 - Se le ha asignado un vehiculo privado
                                        ','3');
Insert into PORTAFOLIO.CHECKIN (ID_CHECKIN,FECHA_CHECKIN,DESCRIPCION,ID_RESERVA) values ('21','2019-11-28','El sr ha iniciado su estadia en el hote a las 14:30 horas del 28 de noviembre 2019 .                                         ','3');
Insert into PORTAFOLIO.CHECKIN (ID_CHECKIN,FECHA_CHECKIN,DESCRIPCION,ID_RESERVA) values ('22','2019-11-28','                                            El sr ha iniciado su estadia en el hotel  a las 14:30 horas del 28 de noviembre 2019 .                                         
                                        - Se le ha asignado un vehiculo privado','3');
Insert into PORTAFOLIO.CHECKIN (ID_CHECKIN,FECHA_CHECKIN,DESCRIPCION,ID_RESERVA) values ('24','2019-11-29','prueba ','13');
Insert into PORTAFOLIO.CHECKIN (ID_CHECKIN,FECHA_CHECKIN,DESCRIPCION,ID_RESERVA) values ('25','2019-11-29','prueba','13');
Insert into PORTAFOLIO.CHECKIN (ID_CHECKIN,FECHA_CHECKIN,DESCRIPCION,ID_RESERVA) values ('26','29/11/2019','                                            prueba
                                        ','13');
Insert into PORTAFOLIO.CHECKIN (ID_CHECKIN,FECHA_CHECKIN,DESCRIPCION,ID_RESERVA) values ('27','29/11/2019','<p style="text-align: left;">prueba</p>
<p style="text-align: left;">Se actualiza la hora de llegada a las 15:30 de la tarde</p>','13');
Insert into PORTAFOLIO.CHECKIN (ID_CHECKIN,FECHA_CHECKIN,DESCRIPCION,ID_RESERVA) values ('28','30/11/2019','<p style="text-align: left;">prueba</p>
<p style="text-align: left;">Se actualiza la hora de llegada a las 15:30 de la tarde</p>
<p style="text-align: left;">El cliente ha contratado servicio de transporte&nbsp;</p>','13');
REM INSERTING into PORTAFOLIO.CHECKOUT
SET DEFINE OFF;
Insert into PORTAFOLIO.CHECKOUT (ID_CHECKOUT,FECHA_CHECKOUT,DESCRIPCION,ID_RESERVA) values ('1','2019-11-29','<p>nueva acta</p>','13');
REM INSERTING into PORTAFOLIO.DEPARTAMENTO
SET DEFINE OFF;
Insert into PORTAFOLIO.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA,DIRECCION,HABILITADO) values ('103','Edificio Santa Clara','Santiago','2','2','155000','Se arrienda departamento acogedor en plaza de la dignidad . ex plaza Italia ','29/11/2019','Av arturo prat 55','0');
Insert into PORTAFOLIO.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA,DIRECCION,HABILITADO) values ('101','Edificio San Diego','Santiago','1','2','270000','                                                                                                                        En arriendo
                                    
                                    
                                    ','2019-11-28','Sargento Aldea 11445','0');
Insert into PORTAFOLIO.DEPARTAMENTO (ID,NOMBRE,UBICACION,BANOS,HABITACIONES,VALORARRIENDO,DESCRIPCION,FECHA,DIRECCION,HABILITADO) values ('104','Edificio San juan','Colchane','3','3','45000','En arriendo','30/11/2019','Matucana 45','1');
REM INSERTING into PORTAFOLIO.INVENTARIO
SET DEFINE OFF;
Insert into PORTAFOLIO.INVENTARIO (ID_INV,ID_DEPTO,PRODUCTO,CANTIDAD,ESTADO,DESCRIPCION,CATEGORIA) values ('66','101','Mesa de madera','1','Activo','  Mesa de centro living
                                    
                                    
                                    
                                    ','Muebleria');
REM INSERTING into PORTAFOLIO.LOCALIDAD
SET DEFINE OFF;
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('323','Arica');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('330','Colchane');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('324','Camarones');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('325','General Lagos');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('326','Putre');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('327','Alto Hospicio');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('328','Iquique');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('329','Camiña');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('331','Huara');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('332','Pica');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('333','Pozo Almonte');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('334','Antofagasta');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('335','Mejillones');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('336','Sierra Gorda');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('337','TalTal');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('338','Calama');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('339','Ollague');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('340','San Pedro de Atacama');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('341','María Elena');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('342','Tocopilla');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('343','Chañaral');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('344','Diego de Almagro');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('345','Caldera');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('346','Copiapo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('347','Tierra Amarilla');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('348','Alto del Camen');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('349','Freirina');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('350','Huasco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('351','Vallenar');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('352','Canela');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('353','Illapel');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('354','Los Vilos');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('355','Salamanca');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('356','Andacollo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('357','Coquimbo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('358','La Higuera');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('359','La Serena');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('360','Paihuaco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('361','Vicuña');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('362','Combarbalá');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('363','Monte Patria');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('364','Ovalle');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('365','Punitaqui');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('366','Río Hurtado');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('367','Isla de Pascua');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('368','Calle Larga');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('369','Los Andes');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('370','Rinconada');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('371','San Esteban');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('372','La Ligua');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('373','Papudo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('374','Petorca');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('375','Zapallar');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('376','Hijuelas');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('377','La Calera');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('378','La Cruz');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('379','Limache');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('380','Nogales');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('381','Olmué');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('382','Quillota');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('383','Algarrobo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('384','Cartagena');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('385','El Quisco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('386','El Tabo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('387','San Antonio');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('388','Santo Domingo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('389','Catemu');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('390','Llaillay');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('391','Panquehue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('392','Putaendo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('393','San Felipe');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('394','Santa Maria');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('395','casablanca');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('396','COncón');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('397','Juan Fernández');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('398','Puchuncaví');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('399','Quilpué');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('400','Quintero');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('401','Valparaiso');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('402','Villa Alemana');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('403','Viña del Mar');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('404','Colina');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('405','Lampa');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('406','TilTil');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('407','Pirque');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('408','Puente Alto');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('409','San José de Maipo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('410','Buin');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('411','Calera de Tango');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('412','Paine');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('413','San Bernardo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('414','Alhué');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('415','Curucaví');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('416','María Pinto');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('417','Melipilla');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('418','San Pedro');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('419','Cerrillos');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('420','Cerro Navia');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('421','Conchalí');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('422','El Bosque');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('423','Estación Central');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('424','Huechuraba');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('425','Independencia');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('426','La Cisterna');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('427','La Granja');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('428','La Florida');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('429','La Pintana');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('430','La Reina');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('431','Las Condes');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('432','Lo Barnechea');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('433','Lo Espejo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('434','Lo Prado');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('435','Macul');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('436','Maipú');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('437','Ñuñoa');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('438','Pedro Aguire Cerda');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('439','Peñalolén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('440','Providencia');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('441','Pudahuel');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('442','Quilicura');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('443','Quinta Normal');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('444','Recoleta');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('445','Renca');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('446','San Miguel');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('447','San Ramón');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('448','Santiago');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('449','Vitacura');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('450','El Monte');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('451','Isla de Maipo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('452','Padre Hurtado');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('453','Peñaflor');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('454','Talagante');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('455','Codegua');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('456','Coínco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('457','Coltauco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('458','Doñihue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('459','Graneros');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('460','Las Cabras');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('461','Machalí');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('462','Malloa');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('463','Mostazal');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('464','Olivar');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('465','Peumo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('466','Pichidegua');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('467','Quinta de Tilcoco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('468','Rancagua');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('469','Rengo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('470','Requínoa');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('471','San Vicente de Tagua Tagua');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('472','La Estrella');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('473','Litueche');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('474','Marchihue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('475','Navidad');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('476','Peredones');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('477','Pichilemu');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('478','Chépica');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('479','Chimbarongo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('480','Lolol');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('481','Nancagua');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('482','Palmilla');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('483','Peralillo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('484','Placilla');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('485','Pumanque');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('486','San Fernando');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('487','Santa Cruz');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('488','Cauquenes');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('489','Chanco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('490','Pelluhue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('491','Curicó');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('492','Hualañe');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('493','Licantén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('494','Molina');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('495','Rauco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('496','Romeral');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('497','Sagrada Familia');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('498','Teno');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('499','Vichulquén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('500','Colbún');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('501','Linares');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('502','Longaví');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('503','Parral');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('504','Retiro');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('505','San Javier');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('506','Villa Alegre');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('507','Yerbas Buenas');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('508','Constitución');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('509','Curepto');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('510','Empedrado');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('511','Maule');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('512','Pelarco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('513','Pencahue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('514','Río Claro');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('515','San Clemente');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('516','San Rafael');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('517','Talca');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('518','Arauco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('519','Cañete');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('520','Contulmo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('521','Curanilahue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('522','Lebu');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('523','Los Álamos');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('524','Tirúa');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('525','Alto Biobío');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('526','Antuco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('527','Cabrero');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('528','Laja');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('529','Los Ángeles');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('530','Mulchén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('531','Negrete');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('532','Quilaco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('533','Quilleco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('534','San Rosendo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('535','Santa Bárbara');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('536','Tucapel');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('537','Yumbel');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('538','Chiguayante');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('539','Concepción');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('540','Coronel');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('541','Nacimiento');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('542','Florida');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('543','Hualpén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('544','Hualqui');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('545','Lota');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('546','Penco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('547','San Pedro de la Paz');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('548','Santa Juana');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('549','Talcahuano');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('550','Tomé');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('551','Bulnes');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('552','Chillan');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('553','Chillan Viejo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('554','Cobquecura');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('555','Coelemu');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('556','Coihueco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('557','El Carmen');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('558','Ninhue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('559','Ñiquen');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('560','Pemuco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('561','Pinto');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('562','Portezuelo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('563','Quillón');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('564','Quirihue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('565','Ránquil');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('566','San Carlos');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('567','San Fabián');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('568','San Ignacio');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('569','San Nicolás');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('570','Treguaco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('571','Yungay');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('572','Carahue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('573','Cholchol');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('574','Cunco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('575','Curarrehue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('576','Freire');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('577','Galvarino');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('578','Gorbea');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('579','Lautaro');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('580','Loncoche');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('581','Melipeuco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('582','Nueva Imperial');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('583','Padre Las Casas');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('584','Perquenco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('585','Pitrufquén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('586','Pucón');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('587','Saavedra');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('588','Temuco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('589','Teodoro Schmidt');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('590','Toltén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('591','Vilcún');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('592','Villarrica');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('593','Angol');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('594','Collipulli');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('595','Curacautín');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('596','Ercilla');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('597','Lonquimay');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('598','Los Saunces');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('599','Lumaco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('600','Purén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('601','Renaico');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('602','Traiguén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('603','Victoria');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('604','Corral');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('605','Lanco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('606','Los Lagos');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('607','Máfil');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('608','Mariquina');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('609','Paillaco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('610','Panquipulli');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('611','Valdivia');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('612','Futrono');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('613','La Unión');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('614','Lago Ranco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('615','Río Bueno');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('616','Ancud');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('617','Castro');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('618','Chonchi');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('619','Curaco de Vélez');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('620','Dalcahue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('621','Puqueldón');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('622','Queilén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('623','Quemchi');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('624','Quellón');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('625','Quinchao');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('626','Calbuco');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('627','Cochamó');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('628','Fresia');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('629','Frutillar');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('630','Llanquihue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('631','Los Muermos');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('632','Maullín');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('633','Puerto Montt');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('634','Puerto Varas');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('635','Osorno');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('636','Puerto Octay');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('637','Purranque');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('638','Puyehue');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('639','Río Negro');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('640','San Juan de la Costa');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('641','San Pablo');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('642','Chaitén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('643','Futaleufú');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('644','Hualaihué');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('645','Palena');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('646','Aisén');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('647','Cisnes');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('648','Guaitecas');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('649','Cochrane');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('650','O''higgins');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('651','Tortel');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('652','Coihaique');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('653','Lago Verde');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('654','Chile Chico');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('655','Río Ibañez');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('656','Antartica');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('657','Cabo de Hornos');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('658','Laguna Blanca');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('659','Punta Arenas');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('660','Río Verde');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('661','San Gregorio');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('662','Porvenir');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('663','Primavera');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('664','Timaukel');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('665','Natales');
Insert into PORTAFOLIO.LOCALIDAD (ID_LOCALIDAD,NOMBRE_LOCALIDAD) values ('666','Torres del Paine');
REM INSERTING into PORTAFOLIO.PLANIFICARTRANSPORTE
SET DEFINE OFF;
Insert into PORTAFOLIO.PLANIFICARTRANSPORTE (ID_PLANIFICACION,ID_SOLICITUD,CONDUCTOR,AUTO,PATENTE) values ('4','4','Juan Perez','Mazda 10','AB543CD');
REM INSERTING into PORTAFOLIO.RESERVA
SET DEFINE OFF;
Insert into PORTAFOLIO.RESERVA (ID_RESERVA,FECHA_RESERVA,CANTIDAD_PERSONAS,FECHA_SALIDA,RUT,ID_DEPARTAMENTO) values ('13','2019-11-28','4','2019-11-30','1111111-1','101');
Insert into PORTAFOLIO.RESERVA (ID_RESERVA,FECHA_RESERVA,CANTIDAD_PERSONAS,FECHA_SALIDA,RUT,ID_DEPARTAMENTO) values ('14','2019-12-01','4','2019-12-19','18213561-6','103');
REM INSERTING into PORTAFOLIO.ROL
SET DEFINE OFF;
Insert into PORTAFOLIO.ROL (ID_ROL,DESCRIPCION) values ('1','Administrador');
Insert into PORTAFOLIO.ROL (ID_ROL,DESCRIPCION) values ('2','Funcionario');
Insert into PORTAFOLIO.ROL (ID_ROL,DESCRIPCION) values ('3','Cliente');
REM INSERTING into PORTAFOLIO.SERV
SET DEFINE OFF;
Insert into PORTAFOLIO.SERV (ID_SERV,FECHA_CONTRATACION,ID_SRV,ID_RESERVA) values ('1','29/11/2019','62','13');
REM INSERTING into PORTAFOLIO.SERVICIO
SET DEFINE OFF;
Insert into PORTAFOLIO.SERVICIO (ID_SRV,NOMBRE_SRV,PRECIO,ID_DEPARTAMENTO) values ('62','Netflix','5600','101');
REM INSERTING into PORTAFOLIO.SOLICITUDTRANSPORTE
SET DEFINE OFF;
Insert into PORTAFOLIO.SOLICITUDTRANSPORTE (ID_SOLICITUD,ID_RESERVA,FECHA_SOLICITUD,HORA_SOLICITUD,ORIGEN,DESTINO,ESTADO) values ('4','14','2019-12-01','22:05','Santiago','Talca','1');
REM INSERTING into PORTAFOLIO.USUARIO
SET DEFINE OFF;
Insert into PORTAFOLIO.USUARIO (ID_USUARIO,RUT,NOMBRE,CORREO,TELEFONO,CLAVE,ID_ROL) values ('388','1-9','Renzo Espeleta','renzo.espeleta@gmail.com','945745586','123','2');
Insert into PORTAFOLIO.USUARIO (ID_USUARIO,RUT,NOMBRE,CORREO,TELEFONO,CLAVE,ID_ROL) values ('383','18213561-5','Manuel Torres  Olivos','alejandro.torresolivos@gmail.com','931378869','123','1');
Insert into PORTAFOLIO.USUARIO (ID_USUARIO,RUT,NOMBRE,CORREO,TELEFONO,CLAVE,ID_ROL) values ('412','18213561-6','Manuel Torres','manu.torreso@alumnos.duoc.cl','931378869','123','3');
Insert into PORTAFOLIO.USUARIO (ID_USUARIO,RUT,NOMBRE,CORREO,TELEFONO,CLAVE,ID_ROL) values ('393','1111111-1','Matias Quezada','mat.quezadav@alumnos.duoc.cl','931378877','123','3');
Insert into PORTAFOLIO.USUARIO (ID_USUARIO,RUT,NOMBRE,CORREO,TELEFONO,CLAVE,ID_ROL) values ('411','1-5','Gonzalez Roberto','gonzalezrobertodc@gmail.com','7822249','123','3');
Insert into PORTAFOLIO.USUARIO (ID_USUARIO,RUT,NOMBRE,CORREO,TELEFONO,CLAVE,ID_ROL) values ('410','1111111-2','Roberto Gonzalez','rober.gonzalez@alumnos.duoc.cl','98458978','123','2');
--------------------------------------------------------
--  DDL for Index LOCALIDADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."LOCALIDADES_PK" ON "PORTAFOLIO"."LOCALIDAD" ("NOMBRE_LOCALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SERVICIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."SERVICIOS_PK" ON "PORTAFOLIO"."SERVICIO" ("ID_SRV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLANIFICARTRANSPORTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."PLANIFICARTRANSPORTE_PK" ON "PORTAFOLIO"."PLANIFICARTRANSPORTE" ("ID_PLANIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger INSERTAR_CATEGORIA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."INSERTAR_CATEGORIA" 
   before insert on "PORTAFOLIO"."CATEGORIA" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select SEQ_ID_INVENTARIO.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "PORTAFOLIO"."INSERTAR_CATEGORIA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVACATEGORIA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVACATEGORIA" 
   before insert on "PORTAFOLIO"."CATEGORIA" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select DEMO_CUST_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVACATEGORIA" DISABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVACONTRATACION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVACONTRATACION" 
   before insert on "PORTAFOLIO"."SERV" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_SERV" is null then 
         select SEQ_CONTRATAR_SERVICIOS.nextval into :NEW."ID_SERV" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVACONTRATACION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVACUENTA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVACUENTA" 
   before insert on "PORTAFOLIO"."USUARIO" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_USUARIO" is null then 
         select INSERTA_USUARIO.nextval into :NEW."ID_USUARIO" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVACUENTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVAPLANIFICACION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVAPLANIFICACION" 
   before insert on "PORTAFOLIO"."PLANIFICARTRANSPORTE" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_PLANIFICACION" is null then 
         select SEQ_SERVICIO.nextval into :NEW."ID_PLANIFICACION" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVAPLANIFICACION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVARESERVA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVARESERVA" 
   before insert on "PORTAFOLIO"."RESERVA" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_RESERVA" is null then 
         select SEQ_IDRESERVA.nextval into :NEW."ID_RESERVA" from dual; 
      end if; 
   end if; 
end;


/
ALTER TRIGGER "PORTAFOLIO"."NUEVARESERVA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVASOLICITUD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVASOLICITUD" 
   before insert on "PORTAFOLIO"."SOLICITUDTRANSPORTE" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_SOLICITUD" is null then 
         select SEQ_CONTRATAR_SERVICIOS.nextval into :NEW."ID_SOLICITUD" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVASOLICITUD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVOCHECK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVOCHECK" 
   before insert on "PORTAFOLIO"."CHECKIN" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_CHECKIN" is null then 
         select SEQ_CHECK_IN.nextval into :NEW."ID_CHECKIN" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVOCHECK" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVOCHECKOUT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVOCHECKOUT" 
   before insert on "PORTAFOLIO"."CHECKOUT" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_CHECKOUT" is null then 
         select SEQ_CHECK_OUT.nextval into :NEW."ID_CHECKOUT" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVOCHECKOUT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVODEPARTAMENTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVODEPARTAMENTO" 
   before insert on "PORTAFOLIO"."DEPARTAMENTO" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select SEQ_ID_DEPARTAMENTO.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVODEPARTAMENTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVOINVENTARIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVOINVENTARIO" 
   before insert on "PORTAFOLIO"."INVENTARIO" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_INV" is null then 
         select SEQ_ID_INVENTARIO.nextval into :NEW."ID_INV" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "PORTAFOLIO"."NUEVOINVENTARIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUEVO_SERVICIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."NUEVO_SERVICIO" 
   before insert on "PORTAFOLIO"."SERVICIO" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_SRV" is null then 
         select USUARIO_SEQUENCIA.nextval into :NEW."ID_SRV" from dual; 
      end if; 
   end if; 
end;


/
ALTER TRIGGER "PORTAFOLIO"."NUEVO_SERVICIO" ENABLE;
--------------------------------------------------------
--  DDL for Procedure P_CONTRATAR_SERVICIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CONTRATAR_SERVICIO" 
( v_id number,
  v_fecha  VARCHAR2,
  v_servicioid VARCHAR2,
  v_reservaid VARCHAR2
) AS 
BEGIN
   insert into serv
  values(v_id , v_fecha,v_servicioid,v_reservaid);
END P_CONTRATAR_SERVICIO;

/
--------------------------------------------------------
--  DDL for Procedure P_CREAR_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CREAR_CATEGORIA" 
( v_categoria VARCHAR2,
  v_id  VARCHAR2 
) AS 
BEGIN
   insert into CATEGORIA
  values(v_categoria , v_id);
END P_CREAR_CATEGORIA;

/
--------------------------------------------------------
--  DDL for Procedure P_CREAR_CHECKIN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CREAR_CHECKIN" 
( v_id number,
  v_fecha  VARCHAR2,
  v_descripcion VARCHAR2,
  v_reservaid VARCHAR2
) AS 
BEGIN
   insert into CHECKIN
  values(v_id , v_fecha,v_descripcion,v_reservaid);
END P_CREAR_CHECKIN;

/
--------------------------------------------------------
--  DDL for Procedure P_CREAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CREAR_CLIENTE" 
( v_id number,
  v_rut  VARCHAR2,
  v_nombre VARCHAR2,
  v_correo VARCHAR2,
  v_telefono VARCHAR2,
  v_clave VARCHAR2,
  v_idrol number
  
) AS 
BEGIN
   insert into USUARIO
  values(v_id , v_rut,v_nombre,v_correo,v_telefono,v_clave,3);
END P_CREAR_CLIENTE;

/
--------------------------------------------------------
--  DDL for Procedure P_CREAR_CUENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CREAR_CUENTA" 
( v_id number,
  v_rut  VARCHAR2,
  v_nombre VARCHAR2,
  v_correo VARCHAR2,
  v_telefono VARCHAR2,
  v_clave VARCHAR2,
  v_idrol number
  
) AS 
BEGIN
   insert into USUARIO
  values(v_id , v_rut,v_nombre,v_correo,v_telefono,v_clave,v_idrol);
END P_CREAR_CUENTA;

/
--------------------------------------------------------
--  DDL for Procedure P_CREAR_DEPARTAMENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CREAR_DEPARTAMENTO" 
( v_id number,
  v_nombre  VARCHAR2,
  v_ubicacion VARCHAR2,
  v_banos VARCHAR2,
  v_habitaciones VARCHAR2,
  v_valorarriendo VARCHAR2,
  v_descripcion VARCHAR2,
  v_fecha VARCHAR2,
  v_direccion VARCHAR2,
  v_habilitado VARCHAR2
) AS 
BEGIN
   insert into DEPARTAMENTO
  values(v_id , v_nombre,v_ubicacion,v_banos,v_habitaciones,v_valorarriendo,v_descripcion,v_fecha,v_direccion,'1');
END P_CREAR_DEPARTAMENTO;

/
--------------------------------------------------------
--  DDL for Procedure P_CREAR_INVENTARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CREAR_INVENTARIO" 
( v_id number,
  v_depto  VARCHAR2,
  v_producto VARCHAR2,
  v_cantidad VARCHAR2,
  v_estado VARCHAR2,
  v_descripcion VARCHAR2,
  v_categoria VARCHAR2
) AS 
BEGIN
   insert into INVENTARIO
  values(v_id , v_depto,v_producto,v_cantidad,v_estado,v_descripcion,v_categoria);
END P_CREAR_INVENTARIO;

/
--------------------------------------------------------
--  DDL for Procedure P_CREAR_LOCALIDAD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CREAR_LOCALIDAD" 
( v_id number,
  V_NOMBRE  VARCHAR2 
) AS 
BEGIN
   insert into LOCALIDAD
  values(v_id , v_nombre);
END P_CREAR_LOCALIDAD;

/
--------------------------------------------------------
--  DDL for Procedure P_CREAR_RESERVA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CREAR_RESERVA" 
( v_id number,
  v_fecha  VARCHAR2,
  v_numeropersonas VARCHAR2,
  v_salida VARCHAR2,
  v_rut VARCHAR2,
  v_departamentoid VARCHAR2
) AS 
BEGIN
   insert into RESERVA
  values(v_id , v_fecha,v_numeropersonas,v_salida,v_rut,v_departamentoid);
END P_CREAR_RESERVA;

/
--------------------------------------------------------
--  DDL for Procedure P_CREAR_SERVICIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_CREAR_SERVICIO" 
( v_id number,
  v_nombre  VARCHAR2,
  v_precio VARCHAR2,
  v_departamentoid number
) AS 
BEGIN
   insert into SERVICIO
  values(v_id , v_nombre,v_precio,v_departamentoid);
END P_CREAR_SERVICIO;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_CATEGORIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_CATEGORIAS" 
(
p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
select * from categoria;
END P_LISTAR_CATEGORIAS;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_CHECKIN_RESERVA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_CHECKIN_RESERVA" 
(
 v_idreserva varchar, p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
select ID_CHECKIN ,FECHA_CHECKIN ,DESCRIPCION ,ID_RESERVA  from checkin where id_reserva=v_idreserva;

END P_LISTAR_CHECKIN_RESERVA;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_CHECKOUT_RESERVA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_CHECKOUT_RESERVA" 
(
 v_idreserva varchar, p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
select ID_CHECKOUT ,FECHA_CHECKOUT ,DESCRIPCION ,ID_RESERVA  from checkout where id_reserva = v_idreserva;

END P_LISTAR_CHECKOUT_RESERVA;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_CLIENTES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_CLIENTES" 
(
p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
Select id_usuario,rut,nombre,correo,telefono,clave,id_rol from usuario WHERE id_rol IN (3);

END P_LISTAR_CLIENTES;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_COMUNAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_COMUNAS" 
(
p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
select * from localidad;
END P_LISTAR_COMUNAS;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_CUENTAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_CUENTAS" 
(
p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
Select id_usuario,rut,nombre,correo,telefono,clave,id_rol from usuario;
END P_LISTAR_CUENTAS;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_DEPARTAMENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_DEPARTAMENTO" 
(
p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
select ID ,NOMBRE ,UBICACION ,BANOS ,HABITACIONES ,VALORARRIENDO ,DESCRIPCION ,FECHA ,DIRECCION ,HABILITADO  from departamento;
END P_LISTAR_DEPARTAMENTO;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_HABILITADOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_HABILITADOS" 
(
p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
select ID ,NOMBRE ,UBICACION ,BANOS ,HABITACIONES ,VALORARRIENDO ,DESCRIPCION ,FECHA ,DIRECCION ,HABILITADO  from departamento where habilitado=1;
END P_LISTAR_HABILITADOS;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_RESERVAS_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_RESERVAS_CLIENTE" 
(
 v_rut VARCHAR2, p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
select r.id_reserva , r.fecha_reserva,r.cantidad_personas,r.fecha_salida,r.rut,r.id_departamento,
                u.id_usuario,u.nombre,u.rut as cedula,d.nombre as residencia , d.ubicacion,d.banos,d.habitaciones,
                d.valorarriendo,d.descripcion,d.fecha from reserva r inner join usuario u on r.rut=u.rut
                inner join departamento d on d.id=r.id_departamento where u.rut  = v_rut;

END P_LISTAR_RESERVAS_CLIENTE;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_RESERVAS_DEPARTAMENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_RESERVAS_DEPARTAMENTO" 
(
 v_id number, p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
select d.id, r.id_reserva , r.rut,u.rut as cedula,u.nombre,d.nombre as departamento,d.ubicacion,r.fecha_reserva,r.fecha_salida
            from departamento d inner join reserva r on r.id_departamento=d.id
                              inner join usuario u on u.rut=r.rut
                              where d.id = v_id;

END P_LISTAR_RESERVAS_DEPARTAMENTO;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_SERVICIOS_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_SERVICIOS_CLIENTE" 
(
 v_idreserva number, p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
select se.id_srv,se.nombre_srv,se.precio from servicio se inner join serv s on se.id_srv=s.id_srv where s.id_reserva = v_idreserva;

END P_LISTAR_SERVICIOS_CLIENTE;

/
--------------------------------------------------------
--  DDL for Procedure P_LISTAR_USUARIOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PORTAFOLIO"."P_LISTAR_USUARIOS" 
(
p_ResultSet  OUT  TYPES.cursorType
)
AS
BEGIN
OPEN p_ResultSet FOR
Select id_usuario,rut,nombre,correo,telefono,clave,id_rol from usuario WHERE id_rol IN (1,2);

END P_LISTAR_USUARIOS;

/
--------------------------------------------------------
--  DDL for Package TYPES
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PORTAFOLIO"."TYPES" 
AS
type cursorType is ref cursor;
END;



/
--------------------------------------------------------
--  DDL for Function ACCESO_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PORTAFOLIO"."ACCESO_USUARIO" (p_rut usuarios.rut %type,p_contrasena usuarios.clave %type)return integer is

p_rut_bd usuarios.rut %type;
p_contrasena_bd usuarios.clave %type;
 BEGIN
select rut, clave into p_rut_bd, p_contrasena_bd from usuarios where rut = p_rut and clave = p_contrasena;
if p_contrasena = p_contrasena_bd and p_rut = p_rut_bd then
 return 1;
 else
 return 0;
 end if;
 exception 
 when NO_DATA_FOUND THEN
 RETURN 0;
 END;

/
--------------------------------------------------------
--  DDL for Function F_RETORNA_NOMBRE
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PORTAFOLIO"."F_RETORNA_NOMBRE" 
(v_correo IN varchar) return varchar 
IS
  v_nombre varchar(200);
BEGIN
  select nombre  into v_nombre
  from usuario
  where CORREO = v_correo;
  return(v_nombre);
END f_retorna_nombre;

/
--------------------------------------------------------
--  DDL for Function F_RETORNA_RUT
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PORTAFOLIO"."F_RETORNA_RUT" 
(v_correo IN varchar) return varchar 
IS
  v_rut varchar(20);
BEGIN
  select rut into v_rut
  from usuario
  where CORREO = v_correo;
  return(v_rut);
END f_retorna_rut;

/
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."ROL" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCALIDAD
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."LOCALIDAD" ADD CONSTRAINT "LOCALIDADES_PK" PRIMARY KEY ("NOMBRE_LOCALIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."LOCALIDAD" MODIFY ("NOMBRE_LOCALIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLANIFICARTRANSPORTE
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PLANIFICARTRANSPORTE" ADD CONSTRAINT "PLANIFICARTRANSPORTE_PK" PRIMARY KEY ("ID_PLANIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."PLANIFICARTRANSPORTE" MODIFY ("ID_PLANIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICIO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."SERVICIO" ADD CONSTRAINT "SERVICIOS_PK" PRIMARY KEY ("ID_SRV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."SERVICIO" MODIFY ("ID_SRV" NOT NULL ENABLE);
